/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BodyIngestFileV1IngestFilePost } from "../types/BodyIngestFileV1IngestFilePost.ts";
import { z } from "zod/v4";

export const bodyIngestFileV1IngestFilePostSchema = z.object({
  file: z.instanceof(File),
  title: z.optional(z.union([z.string(), z.null()])),
  source: z.optional(z.enum(["local", "web", "other"]).default("local")),
  owner: z.optional(z.union([z.string(), z.null()])),
}) as unknown as z.ZodType<BodyIngestFileV1IngestFilePost>;
