/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodyIngestFileV1IngestFilePost } from "../types/BodyIngestFileV1IngestFilePost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const bodyIngestFileV1IngestFilePostSchema = z.object({
    "file": z.string(),
"title": z.union([z.string(), z.null()]).optional(),
"source": z.enum(["local", "web", "other"]).default("local"),
"owner": z.union([z.string(), z.null()]).optional()
    }) as unknown as ToZod<BodyIngestFileV1IngestFilePost>