/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CitationOut } from "../types/CitationOut.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const citationOutSchema = z.object({
    "document_id": z.string(),
"title": z.string(),
"chunk_id": z.string(),
"snippet": z.string(),
"score": z.number(),
"source": z.string().default("local")
    }) as unknown as ToZod<CitationOut>