/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CitationOut } from "../types/CitationOut.ts";
import { z } from "zod/v4";

export const citationOutSchema = z.object({
  document_id: z.string(),
  title: z.string(),
  chunk_id: z.string(),
  snippet: z.string(),
  score: z.number(),
  source: z.optional(z.string().default("local")),
}) as unknown as z.ZodType<CitationOut>;
