/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DocumentIn } from "../types/DocumentIn.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const documentInSchema = z.object({
    "id": z.union([z.string(), z.null()]).optional(),
"title": z.string().min(1).max(1000),
"text": z.string().min(1).max(1000000),
"metadata": z.object({
    
    }).catchall(z.any()).optional(),
"source": z.enum(["local", "web", "other"]).default("local"),
"priority": z.number().int().min(0).max(1000).default(100),
"owner": z.union([z.string(), z.null()]).optional()
    }) as unknown as ToZod<DocumentIn>