/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentIn } from "../types/DocumentIn.ts";
import { z } from "zod/v4";

export const documentInSchema = z.object({
  id: z.optional(z.union([z.string(), z.null()])),
  title: z.string().min(1).max(1000),
  text: z.string().min(1).max(1000000),
  metadata: z.optional(z.object({}).catchall(z.any())),
  source: z.optional(z.enum(["local", "web", "other"]).default("local")),
  priority: z.optional(z.int().min(0).max(1000).default(100)),
  owner: z.optional(z.union([z.string(), z.null()])),
}) as unknown as z.ZodType<DocumentIn>;
