/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HealthResponse } from "../types/HealthResponse.ts";
import { z } from "zod/v4";

/**
 * @description Liveness probe payload.
 */
export const healthResponseSchema = z
  .object({
    status: z.optional(z.string().default("ok")),
  })
  .describe("Liveness probe payload.") as unknown as z.ZodType<HealthResponse>;
