/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  HealthzHealthzGet200,
  HealthzHealthzGetQueryResponse,
} from "../types/HealthzHealthzGet.ts";
import { healthResponseSchema } from "./healthResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const healthzHealthzGet200Schema = z
  .lazy(() => healthResponseSchema)
  .describe("Liveness probe payload.") as unknown as z.ZodType<HealthzHealthzGet200>;

export const healthzHealthzGetQueryResponseSchema = z.lazy(
  () => healthzHealthzGet200Schema,
) as unknown as z.ZodType<HealthzHealthzGetQueryResponse>;
