/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthResponse } from "../types/HealthResponse.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Liveness probe payload.
 */
export const healthResponseSchema = z.object({
    "status": z.string().default("ok")
    }).describe("Liveness probe payload.") as unknown as ToZod<HealthResponse>