/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthzHealthzGet200, HealthzHealthzGetQueryResponse } from "../types/HealthzHealthzGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const healthzHealthzGet200Schema = z.object({
    
    }).catchall(z.any()) as unknown as ToZod<HealthzHealthzGet200>

export const healthzHealthzGetQueryResponseSchema = z.lazy(() => healthzHealthzGet200Schema) as unknown as ToZod<HealthzHealthzGetQueryResponse>