/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../types/HTTPValidationError.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { validationErrorSchema } from "./validationErrorSchema.ts";
import { z } from "zod";

export const HTTPValidationErrorSchema = z.object({
    "detail": z.array(z.lazy(() => validationErrorSchema)).optional()
    }) as unknown as ToZod<HTTPValidationError>