/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IngestRequest } from "../types/IngestRequest.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { documentInSchema } from "./documentInSchema.ts";
import { z } from "zod";

export const ingestRequestSchema = z.object({
    "documents": z.array(z.lazy(() => documentInSchema)).min(1).max(100)
    }) as unknown as ToZod<IngestRequest>