/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IngestResponse } from "../types/IngestResponse.ts";
import { z } from "zod/v4";

export const ingestResponseSchema = z.object({
  document_ids: z.array(z.string()),
  chunks_indexed: z.int(),
  skipped: z.int(),
}) as unknown as z.ZodType<IngestResponse>;
