/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IngestFileV1IngestFilePost200, IngestFileV1IngestFilePost422, IngestFileV1IngestFilePostMutationRequest, IngestFileV1IngestFilePostMutationResponse } from "../types/IngestFileV1IngestFilePost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { bodyIngestFileV1IngestFilePostSchema } from "./bodyIngestFileV1IngestFilePostSchema.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { ingestResponseSchema } from "./ingestResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const ingestFileV1IngestFilePost200Schema = z.lazy(() => ingestResponseSchema) as unknown as ToZod<IngestFileV1IngestFilePost200>

/**
 * @description Validation Error
 */
export const ingestFileV1IngestFilePost422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<IngestFileV1IngestFilePost422>

export const ingestFileV1IngestFilePostMutationRequestSchema = z.lazy(() => bodyIngestFileV1IngestFilePostSchema) as unknown as ToZod<IngestFileV1IngestFilePostMutationRequest>

export const ingestFileV1IngestFilePostMutationResponseSchema = z.lazy(() => ingestFileV1IngestFilePost200Schema) as unknown as ToZod<IngestFileV1IngestFilePostMutationResponse>