/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IngestIngestPost200, IngestIngestPost422, IngestIngestPostMutationRequest, IngestIngestPostMutationResponse } from "../types/IngestIngestPost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { ingestRequestSchema } from "./ingestRequestSchema.ts";
import { ingestResponseSchema } from "./ingestResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const ingestIngestPost200Schema = z.lazy(() => ingestResponseSchema) as unknown as ToZod<IngestIngestPost200>

/**
 * @description Validation Error
 */
export const ingestIngestPost422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<IngestIngestPost422>

export const ingestIngestPostMutationRequestSchema = z.lazy(() => ingestRequestSchema) as unknown as ToZod<IngestIngestPostMutationRequest>

export const ingestIngestPostMutationResponseSchema = z.lazy(() => ingestIngestPost200Schema) as unknown as ToZod<IngestIngestPostMutationResponse>