/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  IngestV1IngestPost200,
  IngestV1IngestPost422,
  IngestV1IngestPostMutationRequest,
  IngestV1IngestPostMutationResponse,
} from "../types/IngestV1IngestPost.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { ingestRequestSchema } from "./ingestRequestSchema.ts";
import { ingestResponseSchema } from "./ingestResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const ingestV1IngestPost200Schema = z.lazy(
  () => ingestResponseSchema,
) as unknown as z.ZodType<IngestV1IngestPost200>;

/**
 * @description Validation Error
 */
export const ingestV1IngestPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<IngestV1IngestPost422>;

export const ingestV1IngestPostMutationRequestSchema = z.lazy(
  () => ingestRequestSchema,
) as unknown as z.ZodType<IngestV1IngestPostMutationRequest>;

export const ingestV1IngestPostMutationResponseSchema = z.lazy(
  () => ingestV1IngestPost200Schema,
) as unknown as z.ZodType<IngestV1IngestPostMutationResponse>;
