/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IngestResponse } from "../types/IngestResponse.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const ingestResponseSchema = z.object({
    "document_ids": z.array(z.string()),
"chunks_indexed": z.number().int(),
"skipped": z.number().int()
    }) as unknown as ToZod<IngestResponse>