/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IngestRequest } from "../types/IngestRequest.ts";
import { documentInSchema } from "./documentInSchema.ts";
import { z } from "zod/v4";

export const ingestRequestSchema = z.object({
  get documents() {
    return z.array(documentInSchema).min(1).max(100);
  },
}) as unknown as z.ZodType<IngestRequest>;
