/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryRequest } from "../types/QueryRequest.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const queryRequestSchema = z.object({
    "question": z.string().min(1).max(10000),
"top_k": z.number().int().min(1).max(20).default(4),
"sources": z.union([z.array(z.enum(["local", "web", "other"])), z.null()]).optional()
    }) as unknown as ToZod<QueryRequest>