/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { QueryRequest } from "../types/QueryRequest.ts";
import { z } from "zod/v4";

export const queryRequestSchema = z.object({
  question: z.string().min(1).max(10000),
  top_k: z.optional(z.int().min(1).max(20).default(4)),
  sources: z.optional(z.union([z.array(z.enum(["local", "web", "other"])), z.null()])),
}) as unknown as z.ZodType<QueryRequest>;
