/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { QueryResponse } from "../types/QueryResponse.ts";
import { citationOutSchema } from "./citationOutSchema.ts";
import { retrievedChunkOutSchema } from "./retrievedChunkOutSchema.ts";
import { z } from "zod/v4";

export const queryResponseSchema = z.object({
  answer: z.string(),
  get citations() {
    return z.array(citationOutSchema);
  },
  get retrieved() {
    return z.array(retrievedChunkOutSchema);
  },
  usage: z.optional(z.union([z.object({}).catchall(z.any()), z.null()])),
}) as unknown as z.ZodType<QueryResponse>;
