/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryV1QueryPost200,
  QueryV1QueryPost422,
  QueryV1QueryPostMutationRequest,
  QueryV1QueryPostMutationResponse,
} from "../types/QueryV1QueryPost.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { queryRequestSchema } from "./queryRequestSchema.ts";
import { queryResponseSchema } from "./queryResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const queryV1QueryPost200Schema = z.lazy(
  () => queryResponseSchema,
) as unknown as z.ZodType<QueryV1QueryPost200>;

/**
 * @description Validation Error
 */
export const queryV1QueryPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<QueryV1QueryPost422>;

export const queryV1QueryPostMutationRequestSchema = z.lazy(
  () => queryRequestSchema,
) as unknown as z.ZodType<QueryV1QueryPostMutationRequest>;

export const queryV1QueryPostMutationResponseSchema = z.lazy(
  () => queryV1QueryPost200Schema,
) as unknown as z.ZodType<QueryV1QueryPostMutationResponse>;
