/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryResponse } from "../types/QueryResponse.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { citationOutSchema } from "./citationOutSchema.ts";
import { retrievedChunkOutSchema } from "./retrievedChunkOutSchema.ts";
import { z } from "zod";

export const queryResponseSchema = z.object({
    "answer": z.string(),
"citations": z.array(z.lazy(() => citationOutSchema)),
"retrieved": z.array(z.lazy(() => retrievedChunkOutSchema)),
"usage": z.union([z.object({
    
    }).catchall(z.any()), z.null()]).optional()
    }) as unknown as ToZod<QueryResponse>