/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryQueryPost200, QueryQueryPost422, QueryQueryPostMutationRequest, QueryQueryPostMutationResponse } from "../types/QueryQueryPost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { queryRequestSchema } from "./queryRequestSchema.ts";
import { queryResponseSchema } from "./queryResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const queryQueryPost200Schema = z.lazy(() => queryResponseSchema) as unknown as ToZod<QueryQueryPost200>

/**
 * @description Validation Error
 */
export const queryQueryPost422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<QueryQueryPost422>

export const queryQueryPostMutationRequestSchema = z.lazy(() => queryRequestSchema) as unknown as ToZod<QueryQueryPostMutationRequest>

export const queryQueryPostMutationResponseSchema = z.lazy(() => queryQueryPost200Schema) as unknown as ToZod<QueryQueryPostMutationResponse>