/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RetrievedChunkOut } from "../types/RetrievedChunkOut.ts";
import { z } from "zod/v4";

export const retrievedChunkOutSchema = z.object({
  chunk_id: z.string(),
  document_id: z.string(),
  title: z.string(),
  ord: z.int(),
  score: z.number(),
  source: z.optional(z.string().default("local")),
}) as unknown as z.ZodType<RetrievedChunkOut>;
