/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RetrievedChunkOut } from "../types/RetrievedChunkOut.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const retrievedChunkOutSchema = z.object({
    "chunk_id": z.string(),
"document_id": z.string(),
"title": z.string(),
"ord": z.number().int(),
"score": z.number(),
"source": z.string().default("local")
    }) as unknown as ToZod<RetrievedChunkOut>