/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StatsV1StatsGet200, StatsV1StatsGetQueryResponse } from "../types/StatsV1StatsGet.ts";
import { statsResponseSchema } from "./statsResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const statsV1StatsGet200Schema = z
  .lazy(() => statsResponseSchema)
  .describe(
    "Store counts plus the active backends (see the ``/stats`` route).",
  ) as unknown as z.ZodType<StatsV1StatsGet200>;

export const statsV1StatsGetQueryResponseSchema = z.lazy(
  () => statsV1StatsGet200Schema,
) as unknown as z.ZodType<StatsV1StatsGetQueryResponse>;
