/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StatsResponse } from "../types/StatsResponse.ts";
import { z } from "zod/v4";

/**
 * @description Store counts plus the active backends (see the ``/stats`` route).
 */
export const statsResponseSchema = z
  .object({
    backend: z.string(),
    documents: z.int(),
    chunks: z.int(),
    embeddings_backend: z.string(),
    llm_backend: z.string(),
    embedding_dim: z.int(),
    search_mode: z.string(),
    reranker: z.string(),
  })
  .describe(
    "Store counts plus the active backends (see the ``/stats`` route).",
  ) as unknown as z.ZodType<StatsResponse>;
