/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StatsResponse } from "../types/StatsResponse.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Store counts plus the active backends (see the ``/stats`` route).
 */
export const statsResponseSchema = z.object({
    "backend": z.string(),
"documents": z.number().int(),
"chunks": z.number().int(),
"embeddings_backend": z.string(),
"llm_backend": z.string(),
"embedding_dim": z.number().int(),
"search_mode": z.string(),
"reranker": z.string()
    }).describe("Store counts plus the active backends (see the ``/stats`` route).") as unknown as ToZod<StatsResponse>