/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ValidationError } from "../types/ValidationError.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const validationErrorSchema = z.object({
    "loc": z.array(z.union([z.number().int(), z.string()])),
"msg": z.string(),
"type": z.string(),
"input": z.any().optional(),
"ctx": z.object({
    
    }).optional()
    }) as unknown as ToZod<ValidationError>