/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EvidenceSourceEnum = "rag" | "web";

/**
 * Evidence
 * @description One piece of retrieved evidence, cited as ``[n]`` in the final answer.
 */
export type Evidence = {
  /**
   * @type string
   */
  source: EvidenceSourceEnum;
  /**
   * @description Document title or URL the content came from
   * @type string
   */
  ref: string;
  /**
   * @type string
   */
  content: string;
  score?: number | null;
};
