/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Response Healthz Healthz Get
 * @description Successful Response
 */
export type HealthzHealthzGet200 = {
  [key: string]: string;
};

export type HealthzHealthzGetQueryResponse = HealthzHealthzGet200;

export type HealthzHealthzGetQuery = {
  Response: HealthzHealthzGet200;
  Errors: any;
};
