/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Evidence } from "./Evidence.ts";

/**
 * ResearchResponse
 * @description Result of a research run: the answer plus its full provenance.
 */
export type ResearchResponse = {
  /**
   * @type string
   */
  answer: string;
  /**
   * @type array
   */
  evidence: Evidence[];
  /**
   * @type array
   */
  trace: string[];
  /**
   * @type integer
   */
  iterations: number;
  /**
   * @description Session id this run was recorded under
   * @type string
   */
  thread_id: string;
};
