/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchRunsPage } from "./ResearchRunsPage.ts";

export type ResearchRunsResearchRunsGetQueryParams = {
    /**
     * @default 20
     * @type integer | undefined
    */
    limit?: number;
    cursor?: (number | null);
};

/**
 * @description Successful Response
*/
export type ResearchRunsResearchRunsGet200 = ResearchRunsPage;

/**
 * @description Validation Error
*/
export type ResearchRunsResearchRunsGet422 = HTTPValidationError;

export type ResearchRunsResearchRunsGetQueryResponse = ResearchRunsResearchRunsGet200;

export type ResearchRunsResearchRunsGetQuery = {
    Response: ResearchRunsResearchRunsGet200;
    QueryParams: ResearchRunsResearchRunsGetQueryParams;
    Errors: ResearchRunsResearchRunsGet422;
};