/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchRequest } from "./ResearchRequest.ts";
import type { ResearchResponse } from "./ResearchResponse.ts";

/**
 * @description Successful Response
*/
export type ResearchResearchPost200 = ResearchResponse;

/**
 * @description Validation Error
*/
export type ResearchResearchPost422 = HTTPValidationError;

export type ResearchResearchPostMutationRequest = ResearchRequest;

export type ResearchResearchPostMutationResponse = ResearchResearchPost200;

export type ResearchResearchPostMutation = {
    Response: ResearchResearchPost200;
    Request: ResearchResearchPostMutationRequest;
    Errors: ResearchResearchPost422;
};