/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description A page of research-run telemetry, newest first, with a keyset cursor.
*/
export type ResearchRunsPage = {
    /**
     * @type array
    */
    items: {
        [key: string]: any;
    }[];
    /**
     * @description Pass back as ?cursor= for the next page; null at the end
    */
    next_cursor?: (number | null);
    /**
     * @description False when no telemetry database is configured
     * @type boolean
    */
    enabled: boolean;
};