/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Evidence } from "./Evidence.ts";

/**
 * ResearchHistoryResponse
 * @description Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).
 */
export type ResearchHistoryResponse = {
  /**
   * @type string
   */
  thread_id: string;
  /**
   * @type boolean
   */
  exists: boolean;
  question?: string | null;
  answer?: string | null;
  /**
   * @type array | undefined
   */
  evidence?: Evidence[];
  /**
   * @type array | undefined
   */
  trace?: string[];
  /**
   * @default 0
   * @type integer | undefined
   */
  iterations?: number;
  /**
   * @description Number of persisted checkpoints (superstep snapshots)
   * @default 0
   * @type integer | undefined
   */
  checkpoints?: number;
};
