/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Evidence } from "./Evidence.ts";

/**
 * ResearchRunOut
 * @description One persisted research-run telemetry row, as returned by the console API.\n\nMirrors ``telemetry.research_runs``: the recorded question/mode/model, the\nanswer with its full provenance (``trace`` + ``evidence``), per-run timing and\nthe durable id/timestamp. Named so ``/openapi.json`` exposes a real schema\ninstead of a free-form object.
 */
export type ResearchRunOut = {
  /**
   * @description Durable row id; also the keyset pagination cursor
   * @type integer
   */
  id: number;
  /**
   * @type string
   */
  thread_id: string;
  /**
   * @type string
   */
  question: string;
  /**
   * @type string
   */
  mode: string;
  model?: string | null;
  /**
   * @type string
   */
  answer: string;
  /**
   * @type integer
   */
  iterations: number;
  /**
   * @type integer
   */
  evidence_count: number;
  /**
   * @type number
   */
  total_ms: number;
  /**
   * @type array | undefined
   */
  trace?: string[];
  /**
   * @type array | undefined
   */
  evidence?: Evidence[];
  /**
   * @type string, date-time
   */
  created_at: string;
};
