/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchRequest } from "./ResearchRequest.ts";
import type { ResearchResponse } from "./ResearchResponse.ts";

/**
 * ResearchResponse
 * @description Successful Response
 */
export type ResearchV1ResearchPost200 = ResearchResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ResearchV1ResearchPost422 = HTTPValidationError;

/**
 * ResearchRequest
 */
export type ResearchV1ResearchPostMutationRequest = ResearchRequest;

export type ResearchV1ResearchPostMutationResponse = ResearchV1ResearchPost200;

export type ResearchV1ResearchPostMutation = {
  Response: ResearchV1ResearchPost200;
  Request: ResearchV1ResearchPostMutationRequest;
  Errors: ResearchV1ResearchPost422;
};
