/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchHistoryResponse } from "./ResearchHistoryResponse.ts";

export type ResearchHistoryV1ResearchHistoryThreadIdGetPathParams = {
    /**
     * @type string
    */
    thread_id: string;
};

/**
 * @description Successful Response
*/
export type ResearchHistoryV1ResearchHistoryThreadIdGet200 = ResearchHistoryResponse;

/**
 * @description Validation Error
*/
export type ResearchHistoryV1ResearchHistoryThreadIdGet422 = HTTPValidationError;

export type ResearchHistoryV1ResearchHistoryThreadIdGetQueryResponse = ResearchHistoryV1ResearchHistoryThreadIdGet200;

export type ResearchHistoryV1ResearchHistoryThreadIdGetQuery = {
    Response: ResearchHistoryV1ResearchHistoryThreadIdGet200;
    PathParams: ResearchHistoryV1ResearchHistoryThreadIdGetPathParams;
    Errors: ResearchHistoryV1ResearchHistoryThreadIdGet422;
};