/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResearchRequestModeEnum = "priority" | "strict";

/**
 * ResearchRequest
 * @description Body of ``POST /research``.
 */
export type ResearchRequest = {
  /**
   * @description Research question to answer
   * @minLength 1
   * @maxLength 4096
   * @type string
   */
  question: string;
  /**
   * @description Hard cap on reflection iterations
   * @minLength 1
   * @maxLength 10
   * @default 3
   * @type integer | undefined
   */
  max_iterations?: number;
  /**
   * @description Session id for durable state. Reuse a prior thread_id to continue that session (resume/audit); omit to start a fresh one.
   */
  thread_id?: string | null;
  /**
   * @description Local-first policy. \'priority\' (default): consult your local data first, web supplements. \'strict\': local only — no web fallback; if local coverage is missing the answer says so.
   * @default "priority"
   * @type string | undefined
   */
  mode?: ResearchRequestModeEnum;
  /**
   * @description Gateway model id to use for this run (planner/reflector/synthesizer). Omit to use the orchestrator\'s configured default.
   */
  model?: string | null;
};
