/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchRunsPage } from "./ResearchRunsPage.ts";

export type ResearchRunsV1ResearchRunsGetQueryParams = {
    /**
     * @default 20
     * @type integer | undefined
    */
    limit?: number;
    cursor?: (number | null);
};

/**
 * @description Successful Response
*/
export type ResearchRunsV1ResearchRunsGet200 = ResearchRunsPage;

/**
 * @description Validation Error
*/
export type ResearchRunsV1ResearchRunsGet422 = HTTPValidationError;

export type ResearchRunsV1ResearchRunsGetQueryResponse = ResearchRunsV1ResearchRunsGet200;

export type ResearchRunsV1ResearchRunsGetQuery = {
    Response: ResearchRunsV1ResearchRunsGet200;
    QueryParams: ResearchRunsV1ResearchRunsGetQueryParams;
    Errors: ResearchRunsV1ResearchRunsGet422;
};