/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchRequest } from "./ResearchRequest.ts";

/**
 * @description Successful Response
*/
export type ResearchStreamResearchStreamPost200 = any;

/**
 * @description Validation Error
*/
export type ResearchStreamResearchStreamPost422 = HTTPValidationError;

export type ResearchStreamResearchStreamPostMutationRequest = ResearchRequest;

export type ResearchStreamResearchStreamPostMutationResponse = ResearchStreamResearchStreamPost200;

export type ResearchStreamResearchStreamPostMutation = {
    Response: ResearchStreamResearchStreamPost200;
    Request: ResearchStreamResearchStreamPostMutationRequest;
    Errors: ResearchStreamResearchStreamPost422;
};