/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchHistoryResponse } from "./ResearchHistoryResponse.ts";

export type ResearchHistoryResearchHistoryThreadIdGetPathParams = {
    /**
     * @type string
    */
    thread_id: string;
};

/**
 * @description Successful Response
*/
export type ResearchHistoryResearchHistoryThreadIdGet200 = ResearchHistoryResponse;

/**
 * @description Validation Error
*/
export type ResearchHistoryResearchHistoryThreadIdGet422 = HTTPValidationError;

export type ResearchHistoryResearchHistoryThreadIdGetQueryResponse = ResearchHistoryResearchHistoryThreadIdGet200;

export type ResearchHistoryResearchHistoryThreadIdGetQuery = {
    Response: ResearchHistoryResearchHistoryThreadIdGet200;
    PathParams: ResearchHistoryResearchHistoryThreadIdGetPathParams;
    Errors: ResearchHistoryResearchHistoryThreadIdGet422;
};