/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ResearchRequest } from "./ResearchRequest.ts";

/**
 * @description Successful Response
 */
export type ResearchStreamV1ResearchStreamPost200 = any;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ResearchStreamV1ResearchStreamPost422 = HTTPValidationError;

/**
 * ResearchRequest
 */
export type ResearchStreamV1ResearchStreamPostMutationRequest = ResearchRequest;

export type ResearchStreamV1ResearchStreamPostMutationResponse =
  ResearchStreamV1ResearchStreamPost200;

export type ResearchStreamV1ResearchStreamPostMutation = {
  Response: ResearchStreamV1ResearchStreamPost200;
  Request: ResearchStreamV1ResearchStreamPostMutationRequest;
  Errors: ResearchStreamV1ResearchStreamPost422;
};
