/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BodyIngestFileV1IngestFilePostSourceEnum = "local" | "web" | "other";

/**
 * Body_ingest_file_v1_ingest_file_post
 */
export type BodyIngestFileV1IngestFilePost = {
  /**
   * @type string
   */
  file: Blob;
  title?: string | null;
  /**
   * @default "local"
   * @type string | undefined
   */
  source?: BodyIngestFileV1IngestFilePostSourceEnum;
  owner?: string | null;
};
