/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type BodyIngestFileV1IngestFilePostSourceEnum = "local" | "web" | "other";

export type BodyIngestFileV1IngestFilePost = {
    /**
     * @type string
    */
    file: string;
    title?: (string | null);
    /**
     * @default "local"
     * @type string | undefined
    */
    source?: BodyIngestFileV1IngestFilePostSourceEnum;
    owner?: (string | null);
};