/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DocumentInSourceEnum = "local" | "web" | "other";

export type DocumentIn = {
    id?: (string | null);
    /**
     * @minLength 1
     * @maxLength 1000
     * @type string
    */
    title: string;
    /**
     * @minLength 1
     * @maxLength 1000000
     * @type string
    */
    text: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: any;
    };
    /**
     * @default "local"
     * @type string | undefined
    */
    source?: DocumentInSourceEnum;
    /**
     * @minLength 0
     * @maxLength 1000
     * @default 100
     * @type integer | undefined
    */
    priority?: number;
    owner?: (string | null);
};