/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HealthResponse } from "./HealthResponse.ts";

/**
 * HealthResponse
 * @description Successful Response
 */
export type HealthzHealthzGet200 = HealthResponse;

export type HealthzHealthzGetQueryResponse = HealthzHealthzGet200;

export type HealthzHealthzGetQuery = {
  Response: HealthzHealthzGet200;
  Errors: any;
};
