/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Liveness probe payload.
*/
export type HealthResponse = {
    /**
     * @default "ok"
     * @type string | undefined
    */
    status?: string;
};