/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { IngestRequest } from "./IngestRequest.ts";
import type { IngestResponse } from "./IngestResponse.ts";

/**
 * @description Successful Response
*/
export type IngestV1IngestPost200 = IngestResponse;

/**
 * @description Validation Error
*/
export type IngestV1IngestPost422 = HTTPValidationError;

export type IngestV1IngestPostMutationRequest = IngestRequest;

export type IngestV1IngestPostMutationResponse = IngestV1IngestPost200;

export type IngestV1IngestPostMutation = {
    Response: IngestV1IngestPost200;
    Request: IngestV1IngestPostMutationRequest;
    Errors: IngestV1IngestPost422;
};