/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { IngestRequest } from "./IngestRequest.ts";
import type { IngestResponse } from "./IngestResponse.ts";

/**
 * @description Successful Response
*/
export type IngestIngestPost200 = IngestResponse;

/**
 * @description Validation Error
*/
export type IngestIngestPost422 = HTTPValidationError;

export type IngestIngestPostMutationRequest = IngestRequest;

export type IngestIngestPostMutationResponse = IngestIngestPost200;

export type IngestIngestPostMutation = {
    Response: IngestIngestPost200;
    Request: IngestIngestPostMutationRequest;
    Errors: IngestIngestPost422;
};