/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DocumentIn } from "./DocumentIn.ts";

export type IngestRequest = {
    /**
     * @type array
    */
    documents: DocumentIn[];
};