/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BodyIngestFileV1IngestFilePost } from "./BodyIngestFileV1IngestFilePost.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { IngestResponse } from "./IngestResponse.ts";

/**
 * IngestResponse
 * @description Successful Response
 */
export type IngestFileV1IngestFilePost200 = IngestResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type IngestFileV1IngestFilePost422 = HTTPValidationError;

/**
 * Body_ingest_file_v1_ingest_file_post
 */
export type IngestFileV1IngestFilePostMutationRequest = BodyIngestFileV1IngestFilePost;

export type IngestFileV1IngestFilePostMutationResponse = IngestFileV1IngestFilePost200;

export type IngestFileV1IngestFilePostMutation = {
  Response: IngestFileV1IngestFilePost200;
  Request: IngestFileV1IngestFilePostMutationRequest;
  Errors: IngestFileV1IngestFilePost422;
};
