/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodyIngestFileV1IngestFilePost } from "./BodyIngestFileV1IngestFilePost.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { IngestResponse } from "./IngestResponse.ts";

/**
 * @description Successful Response
*/
export type IngestFileV1IngestFilePost200 = IngestResponse;

/**
 * @description Validation Error
*/
export type IngestFileV1IngestFilePost422 = HTTPValidationError;

export type IngestFileV1IngestFilePostMutationRequest = BodyIngestFileV1IngestFilePost;

export type IngestFileV1IngestFilePostMutationResponse = IngestFileV1IngestFilePost200;

export type IngestFileV1IngestFilePostMutation = {
    Response: IngestFileV1IngestFilePost200;
    Request: IngestFileV1IngestFilePostMutationRequest;
    Errors: IngestFileV1IngestFilePost422;
};