/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * IngestResponse
 */
export type IngestResponse = {
  /**
   * @type array
   */
  document_ids: string[];
  /**
   * @type integer
   */
  chunks_indexed: number;
  /**
   * @type integer
   */
  skipped: number;
};
