/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type QueryRequestSourcesEnum = "local" | "web" | "other";

export type QueryRequest = {
    /**
     * @minLength 1
     * @maxLength 10000
     * @type string
    */
    question: string;
    /**
     * @minLength 1
     * @maxLength 20
     * @default 4
     * @type integer | undefined
    */
    top_k?: number;
    sources?: (QueryRequestSourcesEnum[] | null);
};