/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { QueryRequest } from "./QueryRequest.ts";
import type { QueryResponse } from "./QueryResponse.ts";

/**
 * @description Successful Response
*/
export type QueryV1QueryPost200 = QueryResponse;

/**
 * @description Validation Error
*/
export type QueryV1QueryPost422 = HTTPValidationError;

export type QueryV1QueryPostMutationRequest = QueryRequest;

export type QueryV1QueryPostMutationResponse = QueryV1QueryPost200;

export type QueryV1QueryPostMutation = {
    Response: QueryV1QueryPost200;
    Request: QueryV1QueryPostMutationRequest;
    Errors: QueryV1QueryPost422;
};