/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CitationOut } from "./CitationOut.ts";
import type { RetrievedChunkOut } from "./RetrievedChunkOut.ts";

/**
 * QueryResponse
 */
export type QueryResponse = {
  /**
   * @type string
   */
  answer: string;
  /**
   * @type array
   */
  citations: CitationOut[];
  /**
   * @type array
   */
  retrieved: RetrievedChunkOut[];
  usage?: {
    [key: string]: any;
  } | null;
};
