/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * RetrievedChunkOut
 */
export type RetrievedChunkOut = {
  /**
   * @type string
   */
  chunk_id: string;
  /**
   * @type string
   */
  document_id: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type integer
   */
  ord: number;
  /**
   * @type number
   */
  score: number;
  /**
   * @default "local"
   * @type string | undefined
   */
  source?: string;
};
