/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StatsResponse } from "./StatsResponse.ts";

/**
 * @description Successful Response
*/
export type StatsStatsGet200 = StatsResponse;

export type StatsStatsGetQueryResponse = StatsStatsGet200;

export type StatsStatsGetQuery = {
    Response: StatsStatsGet200;
    Errors: any;
};