/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Store counts plus the active backends (see the ``/stats`` route).
*/
export type StatsResponse = {
    /**
     * @type string
    */
    backend: string;
    /**
     * @type integer
    */
    documents: number;
    /**
     * @type integer
    */
    chunks: number;
    /**
     * @type string
    */
    embeddings_backend: string;
    /**
     * @type string
    */
    llm_backend: string;
    /**
     * @type integer
    */
    embedding_dim: number;
    /**
     * @type string
    */
    search_mode: string;
    /**
     * @type string
    */
    reranker: string;
};