/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StatsResponse } from "./StatsResponse.ts";

/**
 * @description Successful Response
*/
export type StatsV1StatsGet200 = StatsResponse;

export type StatsV1StatsGetQueryResponse = StatsV1StatsGet200;

export type StatsV1StatsGetQuery = {
    Response: StatsV1StatsGet200;
    Errors: any;
};