/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type StatsStatsGet200 = {
    [key: string]: any;
};

export type StatsStatsGetQueryResponse = StatsStatsGet200;

export type StatsStatsGetQuery = {
    Response: StatsStatsGet200;
    Errors: any;
};