/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CatalogEntry } from "../types/CatalogEntry.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { modelPricingSchema } from "./modelPricingSchema.ts";
import { z } from "zod";

/**
 * @description Rich metadata for one aliased model (beyond the OpenAI /v1/models shape).
 */
export const catalogEntrySchema = z.object({
    "id": z.string(),
"provider": z.string(),
"status": z.string(),
"latency_ms": z.union([z.number(), z.null()]).optional(),
"pricing": z.lazy(() => modelPricingSchema).describe("USD cost per 1k tokens for a model."),
"context_window": z.union([z.number().int(), z.null()]).optional(),
"fallbacks": z.array(z.string()).optional(),
"streaming": z.boolean().default(true)
    }).describe("Rich metadata for one aliased model (beyond the OpenAI /v1/models shape).") as unknown as ToZod<CatalogEntry>