/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CatalogEntry } from "../types/CatalogEntry.ts";
import { modelPricingSchema } from "./modelPricingSchema.ts";
import { z } from "zod/v4";

/**
 * @description Rich metadata for one aliased model (beyond the OpenAI /v1/models shape).
 */
export const catalogEntrySchema = z
  .object({
    id: z.string(),
    provider: z.string(),
    status: z.string(),
    latency_ms: z.optional(z.union([z.number(), z.null()])),
    get pricing() {
      return modelPricingSchema.describe("USD cost per 1k tokens for a model.");
    },
    context_window: z.optional(z.union([z.int(), z.null()])),
    fallbacks: z.optional(z.array(z.string())),
    streaming: z.optional(z.boolean().default(true)),
  })
  .describe(
    "Rich metadata for one aliased model (beyond the OpenAI /v1/models shape).",
  ) as unknown as z.ZodType<CatalogEntry>;
