/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ChatCompletionsV1ChatCompletionsPost200,
  ChatCompletionsV1ChatCompletionsPost422,
  ChatCompletionsV1ChatCompletionsPostMutationRequest,
  ChatCompletionsV1ChatCompletionsPostMutationResponse,
} from "../types/ChatCompletionsV1ChatCompletionsPost.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { chatCompletionRequestSchema } from "./chatCompletionRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const chatCompletionsV1ChatCompletionsPost200Schema =
  z.any() as unknown as z.ZodType<ChatCompletionsV1ChatCompletionsPost200>;

/**
 * @description Validation Error
 */
export const chatCompletionsV1ChatCompletionsPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<ChatCompletionsV1ChatCompletionsPost422>;

export const chatCompletionsV1ChatCompletionsPostMutationRequestSchema = z
  .lazy(() => chatCompletionRequestSchema)
  .describe(
    "Subset of the OpenAI chat completion request we support.",
  ) as unknown as z.ZodType<ChatCompletionsV1ChatCompletionsPostMutationRequest>;

export const chatCompletionsV1ChatCompletionsPostMutationResponseSchema = z.lazy(
  () => chatCompletionsV1ChatCompletionsPost200Schema,
) as unknown as z.ZodType<ChatCompletionsV1ChatCompletionsPostMutationResponse>;
