/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatMessage } from "../types/ChatMessage.ts";
import { z } from "zod/v4";

/**
 * @description A single chat message in OpenAI format.
 */
export const chatMessageSchema = z
  .object({
    role: z.string().regex(/^(system|user|assistant|tool)$/),
    content: z.string(),
  })
  .describe("A single chat message in OpenAI format.") as unknown as z.ZodType<ChatMessage>;
