/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatMessage } from "../types/ChatMessage.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description A single chat message in OpenAI format.
 */
export const chatMessageSchema = z.object({
    "role": z.string().regex(/^(system|user|assistant|tool)$/),
"content": z.string()
    }).describe("A single chat message in OpenAI format.") as unknown as ToZod<ChatMessage>