/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatCompletionRequest } from "../types/ChatCompletionRequest.ts";
import { chatMessageSchema } from "./chatMessageSchema.ts";
import { z } from "zod/v4";

/**
 * @description Subset of the OpenAI chat completion request we support.
 */
export const chatCompletionRequestSchema = z
  .object({
    model: z.string(),
    get messages() {
      return z.array(chatMessageSchema.describe("A single chat message in OpenAI format.")).min(1);
    },
    temperature: z.optional(z.union([z.number(), z.null()])),
    max_tokens: z.optional(z.union([z.int(), z.null()])),
    stream: z.optional(z.boolean().default(false)),
  })
  .describe(
    "Subset of the OpenAI chat completion request we support.",
  ) as unknown as z.ZodType<ChatCompletionRequest>;
