/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatCompletionRequest } from "../types/ChatCompletionRequest.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { chatMessageSchema } from "./chatMessageSchema.ts";
import { z } from "zod";

/**
 * @description Subset of the OpenAI chat completion request we support.
 */
export const chatCompletionRequestSchema = z.object({
    "model": z.string(),
"messages": z.array(z.lazy(() => chatMessageSchema).describe("A single chat message in OpenAI format.")).min(1),
"temperature": z.union([z.number(), z.null()]).optional(),
"max_tokens": z.union([z.number().int(), z.null()]).optional(),
"stream": z.boolean().default(false)
    }).describe("Subset of the OpenAI chat completion request we support.") as unknown as ToZod<ChatCompletionRequest>