/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListModelsV1ModelsGet200,
  ListModelsV1ModelsGetQueryResponse,
} from "../types/ListModelsV1ModelsGet.ts";
import { modelListSchema } from "./modelListSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const listModelsV1ModelsGet200Schema = z
  .lazy(() => modelListSchema)
  .describe("Response of /v1/models.") as unknown as z.ZodType<ListModelsV1ModelsGet200>;

export const listModelsV1ModelsGetQueryResponseSchema = z.lazy(
  () => listModelsV1ModelsGet200Schema,
) as unknown as z.ZodType<ListModelsV1ModelsGetQueryResponse>;
