/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelInfo } from "../types/ModelInfo.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Entry of the /v1/models listing.
 */
export const modelInfoSchema = z.object({
    "id": z.string(),
"object": z.string().default("model"),
"created": z.number().int().optional(),
"owned_by": z.string().default("llm-gateway")
    }).describe("Entry of the /v1/models listing.") as unknown as ToZod<ModelInfo>