/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelPricing } from "../types/ModelPricing.ts";
import { z } from "zod/v4";

/**
 * @description USD cost per 1k tokens for a model.
 */
export const modelPricingSchema = z
  .object({
    input_per_1k: z.number(),
    output_per_1k: z.number(),
  })
  .describe("USD cost per 1k tokens for a model.") as unknown as z.ZodType<ModelPricing>;
