/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelList } from "../types/ModelList.ts";
import { modelInfoSchema } from "./modelInfoSchema.ts";
import { z } from "zod/v4";

/**
 * @description Response of /v1/models.
 */
export const modelListSchema = z
  .object({
    object: z.optional(z.string().default("list")),
    get data() {
      return z.array(modelInfoSchema.describe("Entry of the /v1/models listing."));
    },
  })
  .describe("Response of /v1/models.") as unknown as z.ZodType<ModelList>;
