/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelRunsPage } from "../types/ModelRunsPage.ts";
import { modelRunOutSchema } from "./modelRunOutSchema.ts";
import { z } from "zod/v4";

/**
 * @description A newest-first page of model-run telemetry with a keyset cursor.\n\n``enabled`` is false (and ``items`` empty) when no telemetry database is\nconfigured; pass ``next_cursor`` back as ``cursor`` for the next page.
 */
export const modelRunsPageSchema = z
  .object({
    get items() {
      return z
        .array(
          modelRunOutSchema.describe(
            "One per-call telemetry row as served by /v1/model-runs (read side).",
          ),
        )
        .optional();
    },
    next_cursor: z.optional(z.union([z.int(), z.null()])),
    enabled: z.boolean(),
  })
  .describe(
    "A newest-first page of model-run telemetry with a keyset cursor.\n\n``enabled`` is false (and ``items`` empty) when no telemetry database is\nconfigured; pass ``next_cursor`` back as ``cursor`` for the next page.",
  ) as unknown as z.ZodType<ModelRunsPage>;
