/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelPingV1ModelsModelIdPingGetPathParams, ModelPingV1ModelsModelIdPingGet200, ModelPingV1ModelsModelIdPingGet422, ModelPingV1ModelsModelIdPingGetQueryResponse } from "../types/ModelPingV1ModelsModelIdPingGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { pingResultSchema } from "./pingResultSchema.ts";
import { z } from "zod";

export const modelPingV1ModelsModelIdPingGetPathParamsSchema = z.object({
    "model_id": z.string()
    }) as unknown as ToZod<ModelPingV1ModelsModelIdPingGetPathParams>

/**
 * @description Successful Response
 */
export const modelPingV1ModelsModelIdPingGet200Schema = z.lazy(() => pingResultSchema).describe("Result of a lightweight reachability probe for one model.") as unknown as ToZod<ModelPingV1ModelsModelIdPingGet200>

/**
 * @description Validation Error
 */
export const modelPingV1ModelsModelIdPingGet422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ModelPingV1ModelsModelIdPingGet422>

export const modelPingV1ModelsModelIdPingGetQueryResponseSchema = z.lazy(() => modelPingV1ModelsModelIdPingGet200Schema) as unknown as ToZod<ModelPingV1ModelsModelIdPingGetQueryResponse>