/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelRunOut } from "../types/ModelRunOut.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description One per-call telemetry row as served by /v1/model-runs (read side).
 */
export const modelRunOutSchema = z.object({
    "id": z.number().int(),
"request_id": z.union([z.string(), z.null()]).optional(),
"provider": z.string(),
"model": z.string(),
"served_model": z.string(),
"status": z.string(),
"streaming": z.boolean(),
"cache_hit": z.boolean(),
"prompt_tokens": z.number().int(),
"completion_tokens": z.number().int(),
"total_tokens": z.number().int(),
"context_window": z.union([z.number().int(), z.null()]).optional(),
"context_used_pct": z.union([z.number(), z.null()]).optional(),
"cost_usd": z.number(),
"total_ms": z.number(),
"error": z.union([z.string(), z.null()]).optional(),
"created_at": z.string().datetime()
    }).describe("One per-call telemetry row as served by /v1/model-runs (read side).") as unknown as ToZod<ModelRunOut>