/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelRunsV1ModelRunsGetQueryParams, ModelRunsV1ModelRunsGet200, ModelRunsV1ModelRunsGet422, ModelRunsV1ModelRunsGetQueryResponse } from "../types/ModelRunsV1ModelRunsGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const modelRunsV1ModelRunsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(20),
"cursor": z.union([z.coerce.number().int(), z.null()]).optional()
    }) as unknown as ToZod<ModelRunsV1ModelRunsGetQueryParams>

/**
 * @description Successful Response
 */
export const modelRunsV1ModelRunsGet200Schema = z.object({
    
    }).catchall(z.any()) as unknown as ToZod<ModelRunsV1ModelRunsGet200>

/**
 * @description Validation Error
 */
export const modelRunsV1ModelRunsGet422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ModelRunsV1ModelRunsGet422>

export const modelRunsV1ModelRunsGetQueryResponseSchema = z.lazy(() => modelRunsV1ModelRunsGet200Schema) as unknown as ToZod<ModelRunsV1ModelRunsGetQueryResponse>