/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ModelRunsV1ModelRunsGet200,
  ModelRunsV1ModelRunsGet422,
  ModelRunsV1ModelRunsGetQueryParams,
  ModelRunsV1ModelRunsGetQueryResponse,
} from "../types/ModelRunsV1ModelRunsGet.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { modelRunsPageSchema } from "./modelRunsPageSchema.ts";
import { z } from "zod/v4";

export const modelRunsV1ModelRunsGetQueryParamsSchema = z.object({
  limit: z.coerce.number().int().default(20),
  cursor: z.optional(z.union([z.coerce.number().int(), z.null()])),
}) as unknown as z.ZodType<ModelRunsV1ModelRunsGetQueryParams>;

/**
 * @description Successful Response
 */
export const modelRunsV1ModelRunsGet200Schema = z
  .lazy(() => modelRunsPageSchema)
  .describe(
    "A newest-first page of model-run telemetry with a keyset cursor.\n\n``enabled`` is false (and ``items`` empty) when no telemetry database is\nconfigured; pass ``next_cursor`` back as ``cursor`` for the next page.",
  ) as unknown as z.ZodType<ModelRunsV1ModelRunsGet200>;

/**
 * @description Validation Error
 */
export const modelRunsV1ModelRunsGet422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<ModelRunsV1ModelRunsGet422>;

export const modelRunsV1ModelRunsGetQueryResponseSchema = z.lazy(
  () => modelRunsV1ModelRunsGet200Schema,
) as unknown as z.ZodType<ModelRunsV1ModelRunsGetQueryResponse>;
