/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelsCatalogV1ModelsCatalogGet200, ModelsCatalogV1ModelsCatalogGetQueryResponse } from "../types/ModelsCatalogV1ModelsCatalogGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { catalogEntrySchema } from "./catalogEntrySchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const modelsCatalogV1ModelsCatalogGet200Schema = z.array(z.lazy(() => catalogEntrySchema).describe("Rich metadata for one aliased model (beyond the OpenAI /v1/models shape).")) as unknown as ToZod<ModelsCatalogV1ModelsCatalogGet200>

export const modelsCatalogV1ModelsCatalogGetQueryResponseSchema = z.lazy(() => modelsCatalogV1ModelsCatalogGet200Schema) as unknown as ToZod<ModelsCatalogV1ModelsCatalogGetQueryResponse>