/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelPricing } from "../types/ModelPricing.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description USD cost per 1k tokens for a model.
 */
export const modelPricingSchema = z.object({
    "input_per_1k": z.number(),
"output_per_1k": z.number()
    }).describe("USD cost per 1k tokens for a model.") as unknown as ToZod<ModelPricing>