/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelRunsPage } from "../types/ModelRunsPage.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { modelRunOutSchema } from "./modelRunOutSchema.ts";
import { z } from "zod";

/**
 * @description A newest-first page of model-run telemetry with a keyset cursor.\n\n``enabled`` is false (and ``items`` empty) when no telemetry database is\nconfigured; pass ``next_cursor`` back as ``cursor`` for the next page.
 */
export const modelRunsPageSchema = z.object({
    "items": z.array(z.lazy(() => modelRunOutSchema).describe("One per-call telemetry row as served by /v1/model-runs (read side).")).optional(),
"next_cursor": z.union([z.number().int(), z.null()]).optional(),
"enabled": z.boolean()
    }).describe("A newest-first page of model-run telemetry with a keyset cursor.\n\n``enabled`` is false (and ``items`` empty) when no telemetry database is\nconfigured; pass ``next_cursor`` back as ``cursor`` for the next page.") as unknown as ToZod<ModelRunsPage>