/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelList } from "../types/ModelList.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { modelInfoSchema } from "./modelInfoSchema.ts";
import { z } from "zod";

/**
 * @description Response of /v1/models.
 */
export const modelListSchema = z.object({
    "object": z.string().default("list"),
"data": z.array(z.lazy(() => modelInfoSchema).describe("Entry of the /v1/models listing."))
    }).describe("Response of /v1/models.") as unknown as ToZod<ModelList>