/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelInfo } from "../types/ModelInfo.ts";
import { z } from "zod/v4";

/**
 * @description Entry of the /v1/models listing.
 */
export const modelInfoSchema = z
  .object({
    id: z.string(),
    object: z.optional(z.string().default("model")),
    created: z.optional(z.int()),
    owned_by: z.optional(z.string().default("llm-gateway")),
  })
  .describe("Entry of the /v1/models listing.") as unknown as z.ZodType<ModelInfo>;
