/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelRunOut } from "../types/ModelRunOut.ts";
import { z } from "zod/v4";

/**
 * @description One per-call telemetry row as served by /v1/model-runs (read side).
 */
export const modelRunOutSchema = z
  .object({
    id: z.int(),
    request_id: z.optional(z.union([z.string(), z.null()])),
    provider: z.string(),
    model: z.string(),
    served_model: z.string(),
    status: z.string(),
    streaming: z.boolean(),
    cache_hit: z.boolean(),
    prompt_tokens: z.int(),
    completion_tokens: z.int(),
    total_tokens: z.int(),
    context_window: z.optional(z.union([z.int(), z.null()])),
    context_used_pct: z.optional(z.union([z.number(), z.null()])),
    cost_usd: z.number(),
    total_ms: z.number(),
    error: z.optional(z.union([z.string(), z.null()])),
    created_at: z.iso.datetime(),
  })
  .describe(
    "One per-call telemetry row as served by /v1/model-runs (read side).",
  ) as unknown as z.ZodType<ModelRunOut>;
