/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PingResult } from "../types/PingResult.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Result of a lightweight reachability probe for one model.
 */
export const pingResultSchema = z.object({
    "id": z.string(),
"provider": z.string(),
"configured": z.boolean(),
"reachable": z.boolean(),
"status": z.string(),
"latency_ms": z.union([z.number(), z.null()]).optional(),
"checked_at": z.number().int().optional()
    }).describe("Result of a lightweight reachability probe for one model.") as unknown as ToZod<PingResult>