/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PingResult } from "../types/PingResult.ts";
import { z } from "zod/v4";

/**
 * @description Result of a lightweight reachability probe for one model.
 */
export const pingResultSchema = z
  .object({
    id: z.string(),
    provider: z.string(),
    configured: z.boolean(),
    reachable: z.boolean(),
    status: z.string(),
    latency_ms: z.optional(z.union([z.number(), z.null()])),
    checked_at: z.optional(z.int()),
  })
  .describe(
    "Result of a lightweight reachability probe for one model.",
  ) as unknown as z.ZodType<PingResult>;
