/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UsageModelRow } from "../types/UsageModelRow.ts";
import { z } from "zod/v4";

/**
 * @description Per-model usage aggregate (requests, tokens, USD cost) inside a report.
 */
export const usageModelRowSchema = z
  .object({
    requests: z.optional(z.int().default(0)),
    prompt_tokens: z.optional(z.int().default(0)),
    completion_tokens: z.optional(z.int().default(0)),
    cost_usd: z.optional(z.number().default(0)),
  })
  .describe(
    "Per-model usage aggregate (requests, tokens, USD cost) inside a report.",
  ) as unknown as z.ZodType<UsageModelRow>;
