/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsageModelRow } from "../types/UsageModelRow.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Per-model usage aggregate (requests, tokens, USD cost) inside a report.
 */
export const usageModelRowSchema = z.object({
    "requests": z.number().int().default(0),
"prompt_tokens": z.number().int().default(0),
"completion_tokens": z.number().int().default(0),
"cost_usd": z.number().default(0)
    }).describe("Per-model usage aggregate (requests, tokens, USD cost) inside a report.") as unknown as ToZod<UsageModelRow>