/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  UsageReportV1UsageGet200,
  UsageReportV1UsageGetQueryResponse,
} from "../types/UsageReportV1UsageGet.ts";
import { usageReportSchema } from "./usageReportSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const usageReportV1UsageGet200Schema = z
  .lazy(() => usageReportSchema)
  .describe(
    "Aggregated usage and USD cost for one API key, per model (/v1/usage).",
  ) as unknown as z.ZodType<UsageReportV1UsageGet200>;

export const usageReportV1UsageGetQueryResponseSchema = z.lazy(
  () => usageReportV1UsageGet200Schema,
) as unknown as z.ZodType<UsageReportV1UsageGetQueryResponse>;
