/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UsageReport } from "../types/UsageReport.ts";
import { usageModelRowSchema } from "./usageModelRowSchema.ts";
import { z } from "zod/v4";

/**
 * @description Aggregated usage and USD cost for one API key, per model (/v1/usage).
 */
export const usageReportSchema = z
  .object({
    object: z.optional(z.string().default("usage")),
    api_key: z.string(),
    requests: z.optional(z.int().default(0)),
    prompt_tokens: z.optional(z.int().default(0)),
    completion_tokens: z.optional(z.int().default(0)),
    cost_usd: z.optional(z.number().default(0)),
    models: z.optional(
      z
        .object({})
        .catchall(
          z
            .lazy(() => usageModelRowSchema)
            .describe("Per-model usage aggregate (requests, tokens, USD cost) inside a report."),
        ),
    ),
  })
  .describe(
    "Aggregated usage and USD cost for one API key, per model (/v1/usage).",
  ) as unknown as z.ZodType<UsageReport>;
