/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsageReport } from "../types/UsageReport.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { usageModelRowSchema } from "./usageModelRowSchema.ts";
import { z } from "zod";

/**
 * @description Aggregated usage and USD cost for one API key, per model (/v1/usage).
 */
export const usageReportSchema = z.object({
    "object": z.string().default("usage"),
"api_key": z.string(),
"requests": z.number().int().default(0),
"prompt_tokens": z.number().int().default(0),
"completion_tokens": z.number().int().default(0),
"cost_usd": z.number().default(0),
"models": z.object({
    
    }).catchall(z.lazy(() => usageModelRowSchema).describe("Per-model usage aggregate (requests, tokens, USD cost) inside a report.")).optional()
    }).describe("Aggregated usage and USD cost for one API key, per model (/v1/usage).") as unknown as ToZod<UsageReport>