/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelPricing } from "./ModelPricing.ts";

/**
 * CatalogEntry
 * @description Rich metadata for one aliased model (beyond the OpenAI /v1/models shape).
 */
export type CatalogEntry = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  provider: string;
  /**
   * @type string
   */
  status: string;
  latency_ms?: number | null;
  /**
   * @description USD cost per 1k tokens for a model.
   * @type object
   */
  pricing: ModelPricing;
  context_window?: number | null;
  /**
   * @type array | undefined
   */
  fallbacks?: string[];
  /**
   * @default true
   * @type boolean | undefined
   */
  streaming?: boolean;
};
