/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatCompletionRequest } from "./ChatCompletionRequest.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

/**
 * @description Successful Response
*/
export type ChatCompletionsV1ChatCompletionsPost200 = any;

/**
 * @description Validation Error
*/
export type ChatCompletionsV1ChatCompletionsPost422 = HTTPValidationError;

export type ChatCompletionsV1ChatCompletionsPostMutationRequest = ChatCompletionRequest;

export type ChatCompletionsV1ChatCompletionsPostMutationResponse = ChatCompletionsV1ChatCompletionsPost200;

export type ChatCompletionsV1ChatCompletionsPostMutation = {
    Response: ChatCompletionsV1ChatCompletionsPost200;
    Request: ChatCompletionsV1ChatCompletionsPostMutationRequest;
    Errors: ChatCompletionsV1ChatCompletionsPost422;
};