/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatMessage } from "./ChatMessage.ts";

/**
 * @description Subset of the OpenAI chat completion request we support.
*/
export type ChatCompletionRequest = {
    /**
     * @type string
    */
    model: string;
    /**
     * @type array
    */
    messages: ChatMessage[];
    temperature?: (number | null);
    max_tokens?: (number | null);
    /**
     * @default false
     * @type boolean | undefined
    */
    stream?: boolean;
};