/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ChatMessage
 * @description A single chat message in OpenAI format.
 */
export type ChatMessage = {
  /**
   * @pattern ^(system|user|assistant|tool)$
   * @type string
   */
  role: string;
  /**
   * @type string
   */
  content: string;
};
