/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description A single chat message in OpenAI format.
*/
export type ChatMessage = {
    /**
     * @pattern ^(system|user|assistant|tool)$
     * @type string
    */
    role: string;
    /**
     * @type string
    */
    content: string;
};