/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ModelList } from "./ModelList.ts";

/**
 * ModelList
 * @description Successful Response
 */
export type ListModelsV1ModelsGet200 = ModelList;

export type ListModelsV1ModelsGetQueryResponse = ListModelsV1ModelsGet200;

export type ListModelsV1ModelsGetQuery = {
  Response: ListModelsV1ModelsGet200;
  Errors: any;
};
