/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CatalogEntry } from "./CatalogEntry.ts";

/**
 * @description Successful Response
*/
export type ModelsCatalogV1ModelsCatalogGet200 = CatalogEntry[];

export type ModelsCatalogV1ModelsCatalogGetQueryResponse = ModelsCatalogV1ModelsCatalogGet200;

export type ModelsCatalogV1ModelsCatalogGetQuery = {
    Response: ModelsCatalogV1ModelsCatalogGet200;
    Errors: any;
};