/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ModelInfo
 * @description Entry of the /v1/models listing.
 */
export type ModelInfo = {
  /**
   * @type string
   */
  id: string;
  /**
   * @default "model"
   * @type string | undefined
   */
  object?: string;
  /**
   * @type integer | undefined
   */
  created?: number;
  /**
   * @default "llm-gateway"
   * @type string | undefined
   */
  owned_by?: string;
};
