/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { ModelRunsPage } from "./ModelRunsPage.ts";

export type ModelRunsV1ModelRunsGetQueryParams = {
    /**
     * @default 20
     * @type integer | undefined
    */
    limit?: number;
    cursor?: (number | null);
};

/**
 * @description Successful Response
*/
export type ModelRunsV1ModelRunsGet200 = ModelRunsPage;

/**
 * @description Validation Error
*/
export type ModelRunsV1ModelRunsGet422 = HTTPValidationError;

export type ModelRunsV1ModelRunsGetQueryResponse = ModelRunsV1ModelRunsGet200;

export type ModelRunsV1ModelRunsGetQuery = {
    Response: ModelRunsV1ModelRunsGet200;
    QueryParams: ModelRunsV1ModelRunsGetQueryParams;
    Errors: ModelRunsV1ModelRunsGet422;
};