/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { PingResult } from "./PingResult.ts";

export type ModelPingV1ModelsModelIdPingGetPathParams = {
  /**
   * @type string
   */
  model_id: string;
};

/**
 * PingResult
 * @description Successful Response
 */
export type ModelPingV1ModelsModelIdPingGet200 = PingResult;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ModelPingV1ModelsModelIdPingGet422 = HTTPValidationError;

export type ModelPingV1ModelsModelIdPingGetQueryResponse = ModelPingV1ModelsModelIdPingGet200;

export type ModelPingV1ModelsModelIdPingGetQuery = {
  Response: ModelPingV1ModelsModelIdPingGet200;
  PathParams: ModelPingV1ModelsModelIdPingGetPathParams;
  Errors: ModelPingV1ModelsModelIdPingGet422;
};
