/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelInfo } from "./ModelInfo.ts";

/**
 * @description Response of /v1/models.
*/
export type ModelList = {
    /**
     * @default "list"
     * @type string | undefined
    */
    object?: string;
    /**
     * @type array
    */
    data: ModelInfo[];
};