/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ModelPricing
 * @description USD cost per 1k tokens for a model.
 */
export type ModelPricing = {
  /**
   * @type number
   */
  input_per_1k: number;
  /**
   * @type number
   */
  output_per_1k: number;
};
