/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ModelRunOut
 * @description One per-call telemetry row as served by /v1/model-runs (read side).
 */
export type ModelRunOut = {
  /**
   * @type integer
   */
  id: number;
  request_id?: string | null;
  /**
   * @type string
   */
  provider: string;
  /**
   * @type string
   */
  model: string;
  /**
   * @type string
   */
  served_model: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type boolean
   */
  streaming: boolean;
  /**
   * @type boolean
   */
  cache_hit: boolean;
  /**
   * @type integer
   */
  prompt_tokens: number;
  /**
   * @type integer
   */
  completion_tokens: number;
  /**
   * @type integer
   */
  total_tokens: number;
  context_window?: number | null;
  context_used_pct?: number | null;
  /**
   * @type number
   */
  cost_usd: number;
  /**
   * @type number
   */
  total_ms: number;
  error?: string | null;
  /**
   * @type string, date-time
   */
  created_at: string;
};
