/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelRunOut } from "./ModelRunOut.ts";

/**
 * @description A newest-first page of model-run telemetry with a keyset cursor.\n\n``enabled`` is false (and ``items`` empty) when no telemetry database is\nconfigured; pass ``next_cursor`` back as ``cursor`` for the next page.
*/
export type ModelRunsPage = {
    /**
     * @type array | undefined
    */
    items?: ModelRunOut[];
    next_cursor?: (number | null);
    /**
     * @type boolean
    */
    enabled: boolean;
};