/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Result of a lightweight reachability probe for one model.
*/
export type PingResult = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    provider: string;
    /**
     * @type boolean
    */
    configured: boolean;
    /**
     * @type boolean
    */
    reachable: boolean;
    /**
     * @type string
    */
    status: string;
    latency_ms?: (number | null);
    /**
     * @type integer | undefined
    */
    checked_at?: number;
};