/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsageModelRow } from "./UsageModelRow.ts";

/**
 * @description Aggregated usage and USD cost for one API key, per model (/v1/usage).
*/
export type UsageReport = {
    /**
     * @default "usage"
     * @type string | undefined
    */
    object?: string;
    /**
     * @type string
    */
    api_key: string;
    /**
     * @default 0
     * @type integer | undefined
    */
    requests?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    prompt_tokens?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    completion_tokens?: number;
    /**
     * @default 0
     * @type number | undefined
    */
    cost_usd?: number;
    /**
     * @type object | undefined
    */
    models?: {
        [key: string]: UsageModelRow;
    };
};