/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type UsageReportV1UsageGet200 = {
    [key: string]: any;
};

export type UsageReportV1UsageGetQueryResponse = UsageReportV1UsageGet200;

export type UsageReportV1UsageGetQuery = {
    Response: UsageReportV1UsageGet200;
    Errors: any;
};