/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsageReport } from "./UsageReport.ts";

/**
 * @description Successful Response
*/
export type UsageReportV1UsageGet200 = UsageReport;

export type UsageReportV1UsageGetQueryResponse = UsageReportV1UsageGet200;

export type UsageReportV1UsageGetQuery = {
    Response: UsageReportV1UsageGet200;
    Errors: any;
};