/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Per-model usage aggregate (requests, tokens, USD cost) inside a report.
*/
export type UsageModelRow = {
    /**
     * @default 0
     * @type integer | undefined
    */
    requests?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    prompt_tokens?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    completion_tokens?: number;
    /**
     * @default 0
     * @type number | undefined
    */
    cost_usd?: number;
};