/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Evidence } from "../types/Evidence.ts";
import { z } from "zod/v4";

/**
 * @description One piece of retrieved evidence, cited as ``[n]`` in the final answer.
 */
export const evidenceSchema = z
  .object({
    source: z.enum(["rag", "web"]),
    ref: z.string().describe("Document title or URL the content came from"),
    content: z.string(),
    score: z.optional(z.union([z.number(), z.null()])),
  })
  .describe(
    "One piece of retrieved evidence, cited as ``[n]`` in the final answer.",
  ) as unknown as z.ZodType<Evidence>;
