/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Evidence } from "../types/Evidence.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description One piece of retrieved evidence, cited as ``[n]`` in the final answer.
 */
export const evidenceSchema = z.object({
    "source": z.enum(["rag", "web"]),
"ref": z.string().describe("Document title or URL the content came from"),
"content": z.string(),
"score": z.union([z.number(), z.null()]).optional()
    }).describe("One piece of retrieved evidence, cited as ``[n]`` in the final answer.") as unknown as ToZod<Evidence>