/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResearchRunsPage } from "../types/ResearchRunsPage.ts";
import { researchRunOutSchema } from "./researchRunOutSchema.ts";
import { z } from "zod/v4";

/**
 * @description A page of research-run telemetry, newest first, with a keyset cursor.
 */
export const researchRunsPageSchema = z
  .object({
    get items() {
      return z.array(
        researchRunOutSchema.describe(
          "One persisted research-run telemetry row, as returned by the console API.\n\nMirrors ``telemetry.research_runs``: the recorded question/mode/model, the\nanswer with its full provenance (``trace`` + ``evidence``), per-run timing and\nthe durable id/timestamp. Named so ``/openapi.json`` exposes a real schema\ninstead of a free-form object.",
        ),
      );
    },
    next_cursor: z.optional(
      z
        .union([z.int(), z.null()])
        .describe("Pass back as ?cursor= for the next page; null at the end"),
    ),
    enabled: z.boolean().describe("False when no telemetry database is configured"),
  })
  .describe(
    "A page of research-run telemetry, newest first, with a keyset cursor.",
  ) as unknown as z.ZodType<ResearchRunsPage>;
