/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchResponse } from "../types/ResearchResponse.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { evidenceSchema } from "./evidenceSchema.ts";
import { z } from "zod";

/**
 * @description Result of a research run: the answer plus its full provenance.
 */
export const researchResponseSchema = z.object({
    "answer": z.string(),
"evidence": z.array(z.lazy(() => evidenceSchema).describe("One piece of retrieved evidence, cited as ``[n]`` in the final answer.")),
"trace": z.array(z.string()),
"iterations": z.number().int(),
"thread_id": z.string().describe("Session id this run was recorded under")
    }).describe("Result of a research run: the answer plus its full provenance.") as unknown as ToZod<ResearchResponse>