/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchStreamResearchStreamPost200, ResearchStreamResearchStreamPost422, ResearchStreamResearchStreamPostMutationRequest, ResearchStreamResearchStreamPostMutationResponse } from "../types/ResearchStreamResearchStreamPost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRequestSchema } from "./researchRequestSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const researchStreamResearchStreamPost200Schema = z.any() as unknown as ToZod<ResearchStreamResearchStreamPost200>

/**
 * @description Validation Error
 */
export const researchStreamResearchStreamPost422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ResearchStreamResearchStreamPost422>

export const researchStreamResearchStreamPostMutationRequestSchema = z.lazy(() => researchRequestSchema).describe("Body of ``POST /research``.") as unknown as ToZod<ResearchStreamResearchStreamPostMutationRequest>

export const researchStreamResearchStreamPostMutationResponseSchema = z.lazy(() => researchStreamResearchStreamPost200Schema) as unknown as ToZod<ResearchStreamResearchStreamPostMutationResponse>