/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResearchRunOut } from "../types/ResearchRunOut.ts";
import { evidenceSchema } from "./evidenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description One persisted research-run telemetry row, as returned by the console API.\n\nMirrors ``telemetry.research_runs``: the recorded question/mode/model, the\nanswer with its full provenance (``trace`` + ``evidence``), per-run timing and\nthe durable id/timestamp. Named so ``/openapi.json`` exposes a real schema\ninstead of a free-form object.
 */
export const researchRunOutSchema = z
  .object({
    id: z.int().describe("Durable row id; also the keyset pagination cursor"),
    thread_id: z.string(),
    question: z.string(),
    mode: z.string(),
    model: z.optional(z.union([z.string(), z.null()])),
    answer: z.string(),
    iterations: z.int(),
    evidence_count: z.int(),
    total_ms: z.number(),
    trace: z.optional(z.array(z.string())),
    get evidence() {
      return z
        .array(
          evidenceSchema.describe(
            "One piece of retrieved evidence, cited as ``[n]`` in the final answer.",
          ),
        )
        .optional();
    },
    created_at: z.iso.datetime(),
  })
  .describe(
    "One persisted research-run telemetry row, as returned by the console API.\n\nMirrors ``telemetry.research_runs``: the recorded question/mode/model, the\nanswer with its full provenance (``trace`` + ``evidence``), per-run timing and\nthe durable id/timestamp. Named so ``/openapi.json`` exposes a real schema\ninstead of a free-form object.",
  ) as unknown as z.ZodType<ResearchRunOut>;
