/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchRunsResearchRunsGetQueryParams, ResearchRunsResearchRunsGet200, ResearchRunsResearchRunsGet422, ResearchRunsResearchRunsGetQueryResponse } from "../types/ResearchRunsResearchRunsGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRunsPageSchema } from "./researchRunsPageSchema.ts";
import { z } from "zod";

export const researchRunsResearchRunsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(20),
"cursor": z.union([z.coerce.number().int(), z.null()]).optional()
    }) as unknown as ToZod<ResearchRunsResearchRunsGetQueryParams>

/**
 * @description Successful Response
 */
export const researchRunsResearchRunsGet200Schema = z.lazy(() => researchRunsPageSchema).describe("A page of research-run telemetry, newest first, with a keyset cursor.") as unknown as ToZod<ResearchRunsResearchRunsGet200>

/**
 * @description Validation Error
 */
export const researchRunsResearchRunsGet422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ResearchRunsResearchRunsGet422>

export const researchRunsResearchRunsGetQueryResponseSchema = z.lazy(() => researchRunsResearchRunsGet200Schema) as unknown as ToZod<ResearchRunsResearchRunsGetQueryResponse>