/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchStreamV1ResearchStreamPost200, ResearchStreamV1ResearchStreamPost422, ResearchStreamV1ResearchStreamPostMutationRequest, ResearchStreamV1ResearchStreamPostMutationResponse } from "../types/ResearchStreamV1ResearchStreamPost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRequestSchema } from "./researchRequestSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const researchStreamV1ResearchStreamPost200Schema = z.any() as unknown as ToZod<ResearchStreamV1ResearchStreamPost200>

/**
 * @description Validation Error
 */
export const researchStreamV1ResearchStreamPost422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ResearchStreamV1ResearchStreamPost422>

export const researchStreamV1ResearchStreamPostMutationRequestSchema = z.lazy(() => researchRequestSchema).describe("Body of ``POST /research``.") as unknown as ToZod<ResearchStreamV1ResearchStreamPostMutationRequest>

export const researchStreamV1ResearchStreamPostMutationResponseSchema = z.lazy(() => researchStreamV1ResearchStreamPost200Schema) as unknown as ToZod<ResearchStreamV1ResearchStreamPostMutationResponse>