/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResearchResponse } from "../types/ResearchResponse.ts";
import { evidenceSchema } from "./evidenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description Result of a research run: the answer plus its full provenance.
 */
export const researchResponseSchema = z
  .object({
    answer: z.string(),
    get evidence() {
      return z.array(
        evidenceSchema.describe(
          "One piece of retrieved evidence, cited as ``[n]`` in the final answer.",
        ),
      );
    },
    trace: z.array(z.string()),
    iterations: z.int(),
    thread_id: z.string().describe("Session id this run was recorded under"),
  })
  .describe(
    "Result of a research run: the answer plus its full provenance.",
  ) as unknown as z.ZodType<ResearchResponse>;
