/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ResearchRunsV1ResearchRunsGet200,
  ResearchRunsV1ResearchRunsGet422,
  ResearchRunsV1ResearchRunsGetQueryParams,
  ResearchRunsV1ResearchRunsGetQueryResponse,
} from "../types/ResearchRunsV1ResearchRunsGet.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRunsPageSchema } from "./researchRunsPageSchema.ts";
import { z } from "zod/v4";

export const researchRunsV1ResearchRunsGetQueryParamsSchema = z.object({
  limit: z.coerce.number().int().default(20),
  cursor: z.optional(z.union([z.coerce.number().int(), z.null()])),
}) as unknown as z.ZodType<ResearchRunsV1ResearchRunsGetQueryParams>;

/**
 * @description Successful Response
 */
export const researchRunsV1ResearchRunsGet200Schema = z
  .lazy(() => researchRunsPageSchema)
  .describe(
    "A page of research-run telemetry, newest first, with a keyset cursor.",
  ) as unknown as z.ZodType<ResearchRunsV1ResearchRunsGet200>;

/**
 * @description Validation Error
 */
export const researchRunsV1ResearchRunsGet422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<ResearchRunsV1ResearchRunsGet422>;

export const researchRunsV1ResearchRunsGetQueryResponseSchema = z.lazy(
  () => researchRunsV1ResearchRunsGet200Schema,
) as unknown as z.ZodType<ResearchRunsV1ResearchRunsGetQueryResponse>;
