/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchHistoryResponse } from "../types/ResearchHistoryResponse.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { evidenceSchema } from "./evidenceSchema.ts";
import { z } from "zod";

/**
 * @description Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).
 */
export const researchHistoryResponseSchema = z.object({
    "thread_id": z.string(),
"exists": z.boolean(),
"question": z.union([z.string(), z.null()]).optional(),
"answer": z.union([z.string(), z.null()]).optional(),
"evidence": z.array(z.lazy(() => evidenceSchema).describe("One piece of retrieved evidence, cited as ``[n]`` in the final answer.")).optional(),
"trace": z.array(z.string()).optional(),
"iterations": z.number().int().default(0),
"checkpoints": z.number().int().default(0).describe("Number of persisted checkpoints (superstep snapshots)")
    }).describe("Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).") as unknown as ToZod<ResearchHistoryResponse>