/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchRunOut } from "../types/ResearchRunOut.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { evidenceSchema } from "./evidenceSchema.ts";
import { z } from "zod";

/**
 * @description One persisted research-run telemetry row, as returned by the console API.\n\nMirrors ``telemetry.research_runs``: the recorded question/mode/model, the\nanswer with its full provenance (``trace`` + ``evidence``), per-run timing and\nthe durable id/timestamp. Named so ``/openapi.json`` exposes a real schema\ninstead of a free-form object.
 */
export const researchRunOutSchema = z.object({
    "id": z.number().int().describe("Durable row id; also the keyset pagination cursor"),
"thread_id": z.string(),
"question": z.string(),
"mode": z.string(),
"model": z.union([z.string(), z.null()]).optional(),
"answer": z.string(),
"iterations": z.number().int(),
"evidence_count": z.number().int(),
"total_ms": z.number(),
"trace": z.array(z.string()).optional(),
"evidence": z.array(z.lazy(() => evidenceSchema).describe("One piece of retrieved evidence, cited as ``[n]`` in the final answer.")).optional(),
"created_at": z.string().datetime()
    }).describe("One persisted research-run telemetry row, as returned by the console API.\n\nMirrors ``telemetry.research_runs``: the recorded question/mode/model, the\nanswer with its full provenance (``trace`` + ``evidence``), per-run timing and\nthe durable id/timestamp. Named so ``/openapi.json`` exposes a real schema\ninstead of a free-form object.") as unknown as ToZod<ResearchRunOut>