/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchResearchPost200, ResearchResearchPost422, ResearchResearchPostMutationRequest, ResearchResearchPostMutationResponse } from "../types/ResearchResearchPost.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRequestSchema } from "./researchRequestSchema.ts";
import { researchResponseSchema } from "./researchResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const researchResearchPost200Schema = z.lazy(() => researchResponseSchema).describe("Result of a research run: the answer plus its full provenance.") as unknown as ToZod<ResearchResearchPost200>

/**
 * @description Validation Error
 */
export const researchResearchPost422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ResearchResearchPost422>

export const researchResearchPostMutationRequestSchema = z.lazy(() => researchRequestSchema).describe("Body of ``POST /research``.") as unknown as ToZod<ResearchResearchPostMutationRequest>

export const researchResearchPostMutationResponseSchema = z.lazy(() => researchResearchPost200Schema) as unknown as ToZod<ResearchResearchPostMutationResponse>