/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResearchHistoryResponse } from "../types/ResearchHistoryResponse.ts";
import { evidenceSchema } from "./evidenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).
 */
export const researchHistoryResponseSchema = z
  .object({
    thread_id: z.string(),
    exists: z.boolean(),
    question: z.optional(z.union([z.string(), z.null()])),
    answer: z.optional(z.union([z.string(), z.null()])),
    get evidence() {
      return z
        .array(
          evidenceSchema.describe(
            "One piece of retrieved evidence, cited as ``[n]`` in the final answer.",
          ),
        )
        .optional();
    },
    trace: z.optional(z.array(z.string())),
    iterations: z.optional(z.int().default(0)),
    checkpoints: z.optional(
      z.int().default(0).describe("Number of persisted checkpoints (superstep snapshots)"),
    ),
  })
  .describe(
    "Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).",
  ) as unknown as z.ZodType<ResearchHistoryResponse>;
