/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchRunsV1ResearchRunsGetQueryParams, ResearchRunsV1ResearchRunsGet200, ResearchRunsV1ResearchRunsGet422, ResearchRunsV1ResearchRunsGetQueryResponse } from "../types/ResearchRunsV1ResearchRunsGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRunsPageSchema } from "./researchRunsPageSchema.ts";
import { z } from "zod";

export const researchRunsV1ResearchRunsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(20),
"cursor": z.union([z.coerce.number().int(), z.null()]).optional()
    }) as unknown as ToZod<ResearchRunsV1ResearchRunsGetQueryParams>

/**
 * @description Successful Response
 */
export const researchRunsV1ResearchRunsGet200Schema = z.lazy(() => researchRunsPageSchema).describe("A page of research-run telemetry, newest first, with a keyset cursor.") as unknown as ToZod<ResearchRunsV1ResearchRunsGet200>

/**
 * @description Validation Error
 */
export const researchRunsV1ResearchRunsGet422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ResearchRunsV1ResearchRunsGet422>

export const researchRunsV1ResearchRunsGetQueryResponseSchema = z.lazy(() => researchRunsV1ResearchRunsGet200Schema) as unknown as ToZod<ResearchRunsV1ResearchRunsGetQueryResponse>