/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchHistoryResearchHistoryThreadIdGetPathParams, ResearchHistoryResearchHistoryThreadIdGet200, ResearchHistoryResearchHistoryThreadIdGet422, ResearchHistoryResearchHistoryThreadIdGetQueryResponse } from "../types/ResearchHistoryResearchHistoryThreadIdGet.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchHistoryResponseSchema } from "./researchHistoryResponseSchema.ts";
import { z } from "zod";

export const researchHistoryResearchHistoryThreadIdGetPathParamsSchema = z.object({
    "thread_id": z.string()
    }) as unknown as ToZod<ResearchHistoryResearchHistoryThreadIdGetPathParams>

/**
 * @description Successful Response
 */
export const researchHistoryResearchHistoryThreadIdGet200Schema = z.lazy(() => researchHistoryResponseSchema).describe("Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).") as unknown as ToZod<ResearchHistoryResearchHistoryThreadIdGet200>

/**
 * @description Validation Error
 */
export const researchHistoryResearchHistoryThreadIdGet422Schema = z.lazy(() => HTTPValidationErrorSchema) as unknown as ToZod<ResearchHistoryResearchHistoryThreadIdGet422>

export const researchHistoryResearchHistoryThreadIdGetQueryResponseSchema = z.lazy(() => researchHistoryResearchHistoryThreadIdGet200Schema) as unknown as ToZod<ResearchHistoryResearchHistoryThreadIdGetQueryResponse>