/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResearchRunsPage } from "../types/ResearchRunsPage.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description A page of research-run telemetry, newest first, with a keyset cursor.
 */
export const researchRunsPageSchema = z.object({
    "items": z.array(z.object({
    
    }).catchall(z.any())),
"next_cursor": z.union([z.number().int(), z.null()]).describe("Pass back as ?cursor= for the next page; null at the end").optional(),
"enabled": z.boolean().describe("False when no telemetry database is configured")
    }).describe("A page of research-run telemetry, newest first, with a keyset cursor.") as unknown as ToZod<ResearchRunsPage>