/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ResearchV1ResearchPost200,
  ResearchV1ResearchPost422,
  ResearchV1ResearchPostMutationRequest,
  ResearchV1ResearchPostMutationResponse,
} from "../types/ResearchV1ResearchPost.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchRequestSchema } from "./researchRequestSchema.ts";
import { researchResponseSchema } from "./researchResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const researchV1ResearchPost200Schema = z
  .lazy(() => researchResponseSchema)
  .describe(
    "Result of a research run: the answer plus its full provenance.",
  ) as unknown as z.ZodType<ResearchV1ResearchPost200>;

/**
 * @description Validation Error
 */
export const researchV1ResearchPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<ResearchV1ResearchPost422>;

export const researchV1ResearchPostMutationRequestSchema = z
  .lazy(() => researchRequestSchema)
  .describe(
    "Body of ``POST /research``.",
  ) as unknown as z.ZodType<ResearchV1ResearchPostMutationRequest>;

export const researchV1ResearchPostMutationResponseSchema = z.lazy(
  () => researchV1ResearchPost200Schema,
) as unknown as z.ZodType<ResearchV1ResearchPostMutationResponse>;
