/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ResearchHistoryV1ResearchHistoryThreadIdGet200,
  ResearchHistoryV1ResearchHistoryThreadIdGet422,
  ResearchHistoryV1ResearchHistoryThreadIdGetPathParams,
  ResearchHistoryV1ResearchHistoryThreadIdGetQueryResponse,
} from "../types/ResearchHistoryV1ResearchHistoryThreadIdGet.ts";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { researchHistoryResponseSchema } from "./researchHistoryResponseSchema.ts";
import { z } from "zod/v4";

export const researchHistoryV1ResearchHistoryThreadIdGetPathParamsSchema = z.object({
  thread_id: z.string(),
}) as unknown as z.ZodType<ResearchHistoryV1ResearchHistoryThreadIdGetPathParams>;

/**
 * @description Successful Response
 */
export const researchHistoryV1ResearchHistoryThreadIdGet200Schema = z
  .lazy(() => researchHistoryResponseSchema)
  .describe(
    "Latest checkpointed snapshot for a ``thread_id`` (empty if unknown).",
  ) as unknown as z.ZodType<ResearchHistoryV1ResearchHistoryThreadIdGet200>;

/**
 * @description Validation Error
 */
export const researchHistoryV1ResearchHistoryThreadIdGet422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
) as unknown as z.ZodType<ResearchHistoryV1ResearchHistoryThreadIdGet422>;

export const researchHistoryV1ResearchHistoryThreadIdGetQueryResponseSchema = z.lazy(
  () => researchHistoryV1ResearchHistoryThreadIdGet200Schema,
) as unknown as z.ZodType<ResearchHistoryV1ResearchHistoryThreadIdGetQueryResponse>;
